### ISSUE TITLE
Undertsand why instagram is 1st social network as ref

### ISSUE THREAD

**Issue by billmetangmo** [mongulu-cm/nje#11]
En voyant que est leur comportement de ceux qui viennent d'Instagram ?

1/ Utiliser l'onglet behaviour de matomo ( en créant un segment instagram) : https://matomo.simplehosting.me
Sur la création des segments: https://matomo.org/docs/segmentation/

2/ Possibilité d'utiliser des logiciels libres additionnels pour avoir https://developer.matomo.org/guides/heatmap-session-recording
Choisir un dans cette liste: https://alternativeto.net/software/hotjar-insights/?license=free

**Comment by GoldenScientist** [comment]
https://geekflare.com/fr/website-session-recording/

**Comment by billmetangmo** [comment]
Alternative à hotjar https://www.inspectlet.com/

**Comment by billmetangmo** [comment]
En 2022, la seule viste venant d'instagram date du 02 janvier 2022. C'était peut-être juste un faux positif
