### ISSUE TITLE
Add support flag for Ukraine ?

### ISSUE THREAD

**Issue by billmetangmo** [mongulu-cm/nje#14]
Ask wether we should or not add https://github.com/virae/we-stand-with-ukraine to our website

**Comment by billmetangmo** [comment]
Drapeau de la paix dans le monde proposé par @DimitriTchapmi  .
https://www.google.com/imgres?imgurl=https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Peace_sign.svg/1200px-Peace_sign.svg.png&imgrefurl=https://fr.wikipedia.org/wiki/Symboles_de_la_paix&tbnid=Zo7uQuhZcKERNM&vet=1&docid=OTpDljM_ysOCUM&w=1200&h=1200&hl=en-US&source=sh/x/im

**Comment by fabiolatagne97** [comment]
Hi every one,
Here is the link to the peace gallery :

![](https://wtf.roflcopter.fr/pics/gallery#ATPBv5jD/5yPFRBae.jpeg,yesgbLKw/7DrSRkYy.jpeg,eKOuw3t2/iNrOdt2s.jpeg,iGllp8DU/FZZ1ZcgJ.jpeg,xCSaTCSv/lFZMSdhR.jpeg,a6mkMYQF/X91FaZ31.jpeg,f6Dc7Icg/czdccAKE.jpeg,rM3j0MgZ/bndzKFeQ.jpeg)

**Comment by billmetangmo** [comment]
Choix de l'image 
![image](https://user-images.githubusercontent.com/25366207/166157393-0f9a3477-1752-4281-9073-7746634b198d.png)

avec les drapeaux du cercle ci-dessous:
![image](https://user-images.githubusercontent.com/25366207/166157405-9f221392-c1a8-4e48-a6dc-86269a783e79.png)

**Comment by billmetangmo** [comment]
@all-contributors please add @DimitriTchapmi for idea
refers to https://github.com/mongulu-cm/nje/issues/14#issuecomment-1079982124

**Comment by billmetangmo** [comment]
Here's the logo image. Thanks to @fabiolatagne97  and @Tchepga 

![image](https://user-images.githubusercontent.com/25366207/168494687-2e40dee0-541e-4e48-b7dd-0ae0ce155ed4.png)
