### ISSUE TITLE
Renew website UI

### ISSUE THREAD

**Issue by billmetangmo** [mongulu-cm/nje#17]
https://www.untitledui.com/
https://tamagui.dev
https://slint-ui.com/
https://ui.mantine.dev

or https://github.com/topics/uikit

if animation needed: https://lottiefiles.com/

**Comment by billmetangmo** [comment]
https://cred.club/neopop

**Comment by billmetangmo** [comment]
https://flowbite.com

**Comment by billmetangmo** [comment]
https://cloudscape.design/components/overview/

**Comment by billmetangmo** [comment]
use jekyll themes https://jamstackthemes.dev 
https://jekyllrb.com/resources/#:~:text=popular%20Jekyll%20resources.-,themes,-GitHub.com%20%23jekyll

**Comment by billmetangmo** [comment]
- Bookshoop from Cloudcannon: https://www.youtube.com/watch?v=BSFDSXU3E-w
- https://open.quiqr.org/
- https://medium.com/quick-code/the-best-10-open-source-headless-cms-2022-f0821a946386

**Comment by billmetangmo** [comment]
do a test with https://github.com/app-generator/rocket-builder

**Comment by tsafacjo** [comment]
@billmetangmo  j'ai fait un push de la version du site web proposé par l'UX designer

**Comment by billmetangmo** [comment]
oki je vais regarder ça

**Comment by billmetangmo** [comment]
J'ai passé tout en français et fait quelques modifications.
Le problème maintenant est de rendre les liens cliquables + le fait que ça ne soit pas responsive son design

**Comment by billmetangmo** [comment]
abandon

**Comment by billmetangmo** [comment]
@tsafacjo j'ai intégré la nouvelle UI
